name: CI

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  eunit:
    name: EUnit ${{matrix.otp}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['24.3', '25.3']
        rebar3: ['3.20']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 eunit

  ct:
    name: Common Tests ${{matrix.otp}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['24.3', '25.3']
        rebar3: ['3.20']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 ct --cover

  cover:
    name: Coverage ${{matrix.otp}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['24.3', '25.3']
        rebar3: ['3.20']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 cover
